const supportedLanguages = [
  'English',
  'Hindi',
  'Kannada',
  'Telugu',
  'Tamil',
  'Marathi',
  'Bengali',
  'Malayalam',
];

const languageCodes = {
  'English': 'en',
  'Hindi': 'hi',
  'Kannada': 'kn',
  'Telugu': 'te',
  'Tamil': 'ta',
  'Marathi': 'mr',
  'Bengali': 'bn',
  'Malayalam': 'ml',
};

const translations = <String, Map<String, String>>{
  'en': {
    'app_name': 'KarigarAI',
    'home_title': 'Bring your craft\nto more people.',
    'add_product': 'Add Product',
    'products': 'My Products',
    'create': 'Create',
    'marketplace': 'Marketplace',
    'profile': 'Profile',
    'draft': 'Draft',
    'ready': 'Ready',
    'published': 'Published',
    'save': 'Save product',
    'settings': 'Settings',
    'welcome_tagline': 'Tradition Meets Technology',
    'welcome_message': 'Turn your handmade products into market-ready digital listings using your voice and photos.',
    'get_started': 'Get Started',
    'existing_account': 'I Already Have an Account',
    'hello_artisan': 'Hello, Artisan',
    'home_support': 'Let us share your craft with the world.',
    'create_new_product': 'Create New Product',
    'create_support': 'Turn your product into a market-ready listing',
    'total_products': 'Total Products',
    'recent_products': 'Recent Products',
    'view_all': 'View All >',
  },
  'hi': {
    'app_name': 'कारीगरAI',
    'home_title': 'अपने शिल्प को\nऔर लोगों तक पहुँचाएँ।',
    'add_product': 'उत्पाद जोड़ें',
    'products': 'मेरे उत्पाद',
    'create': 'बनाएँ',
    'marketplace': 'बाज़ार',
    'profile': 'प्रोफ़ाइल',
    'draft': 'ड्राफ्ट',
    'ready': 'तैयार',
    'published': 'प्रकाशित',
    'save': 'उत्पाद सहेजें',
    'settings': 'सेटिंग्स',
    'welcome_tagline': 'परंपरा और प्रौद्योगिकी',
    'welcome_message': 'अपनी आवाज़ और तस्वीरों से अपने हस्तनिर्मित उत्पादों की बाज़ार-तैयार डिजिटल सूची बनाएं।',
    'get_started': 'शुरू करें',
    'existing_account': 'मेरा पहले से खाता है',
    'hello_artisan': 'नमस्ते, कारीगर',
    'home_support': 'आइए आपकी कला को दुनिया तक पहुँचाएँ।',
    'create_new_product': 'नया उत्पाद बनाएं',
    'create_support': 'अपने उत्पाद को बाज़ार-तैयार सूची में बदलें',
    'total_products': 'कुल उत्पाद',
    'recent_products': 'हाल के उत्पाद',
    'view_all': 'सभी देखें >',
  },
  'kn': {
    'app_name': 'ಕರಿಗರ್AI',
    'home_title': 'ನಿಮ್ಮ ಕರಕುಶಲವನ್ನು\nಹೆಚ್ಚಿನ ಜನರಿಗೆ ತಲುಪಿಸಿ.',
    'add_product': 'ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    'products': 'ನನ್ನ ಉತ್ಪನ್ನಗಳು',
    'create': 'ರಚಿಸಿ',
    'marketplace': 'ಮಾರುಕಟ್ಟೆ',
    'profile': 'ಪ್ರೊಫೈಲ್',
    'draft': 'ಕರಡು',
    'ready': 'ಸಿದ್ಧ',
    'published': 'ಪ್ರಕಟಿಸಲಾಗಿದೆ',
    'save': 'ಉತ್ಪನ್ನ ಉಳಿಸಿ',
    'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'welcome_tagline': 'ಸಂಪ್ರದಾಯ ಮತ್ತು ತಂತ್ರಜ್ಞಾನ',
    'welcome_message': 'ನಿಮ್ಮ ಧ್ವನಿ ಮತ್ತು ಚಿತ್ರಗಳನ್ನು ಬಳಸಿ ಕೈತಯಾರಿಸಿದ ಉತ್ಪನ್ನಗಳಿಗೆ ಮಾರುಕಟ್ಟೆ-ಸಿದ್ಧ ಪಟ್ಟಿ ರಚಿಸಿ.',
    'get_started': 'ಪ್ರಾರಂಭಿಸಿ',
    'existing_account': 'ನನಗೆ ಈಗಾಗಲೇ ಖಾತೆ ಇದೆ',
    'hello_artisan': 'ನಮಸ್ಕಾರ, ಕುಶಲಕರ್ಮಿ',
    'home_support': 'ನಿಮ್ಮ ಕಲೆಯನ್ನು ಜಗತ್ತಿಗೆ ತಲುಪಿಸೋಣ.',
    'create_new_product': 'ಹೊಸ ಉತ್ಪನ್ನ ರಚಿಸಿ',
    'create_support': 'ನಿಮ್ಮ ಉತ್ಪನ್ನವನ್ನು ಮಾರುಕಟ್ಟೆ-ಸಿದ್ಧ ಪಟ್ಟಿಯನ್ನಾಗಿ ಮಾಡಿ',
    'total_products': 'ಒಟ್ಟು ಉತ್ಪನ್ನಗಳು',
    'recent_products': 'ಇತ್ತೀಚಿನ ಉತ್ಪನ್ನಗಳು',
    'view_all': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ >',
  },
  'te': {
    'app_name': 'కరిగర్AI',
    'home_title': 'మీ కళను\nమరింత మందికి చేరవేయండి.',
    'add_product': 'ఉత్పత్తిని జోడించండి',
    'products': 'నా ఉత్పత్తులు',
    'create': 'సృష్టించండి',
    'marketplace': 'మార్కెట్',
    'profile': 'ప్రొఫైల్',
    'draft': 'చిత్తుప్రతి',
    'ready': 'సిద్ధం',
    'published': 'ప్రచురించబడింది',
    'save': 'ఉత్పత్తిని సేవ్ చేయండి',
    'settings': 'సెట్టింగ్‌లు',
    'welcome_tagline': 'సంప్రదాయం మరియు సాంకేతికత',
    'welcome_message': 'మీ స్వరం మరియు ఫోటోలతో చేతితో తయారుచేసిన ఉత్పత్తులకు మార్కెట్-సిద్ధమైన డిజిటల్ జాబితాలను రూపొందించండి.',
    'get_started': 'ప్రారంభించండి',
    'existing_account': 'నాకు ఇప్పటికే ఖాతా ఉంది',
    'hello_artisan': 'నమస్కారం, కళాకారుడు',
    'home_support': 'మీ కళను ప్రపంచానికి చేరవేద్దాం.',
    'create_new_product': 'కొత్త ఉత్పత్తిని సృష్టించండి',
    'create_support': 'మీ ఉత్పత్తిని మార్కెట్-సిద్ధమైన జాబితాగా మార్చండి',
    'total_products': 'మొత్తం ఉత్పత్తులు',
    'recent_products': 'ఇటీవలి ఉత్పత్తులు',
    'view_all': 'అన్నీ చూడండి >',
  },
  'ta': {
    'app_name': 'கரிகர்AI',
    'home_title': 'உங்கள் கைவினையை\nமேலும் பலரிடம் கொண்டு செல்லுங்கள்.',
    'add_product': 'தயாரிப்பைச் சேர்க்கவும்',
    'products': 'என் தயாரிப்புகள்',
    'create': 'உருவாக்கு',
    'marketplace': 'சந்தை',
    'profile': 'சுயவிவரம்',
    'draft': 'வரைவு',
    'ready': 'தயார்',
    'published': 'வெளியிடப்பட்டது',
    'save': 'தயாரிப்பைச் சேமி',
    'settings': 'அமைப்புகள்',
    'welcome_tagline': 'பாரம்பரியமும் தொழில்நுட்பமும்',
    'welcome_message': 'உங்கள் குரல் மற்றும் புகைப்படங்களைப் பயன்படுத்தி கைவினைப் பொருட்களுக்கான சந்தைத் தயாரான பட்டியல்களை உருவாக்குங்கள்.',
    'get_started': 'தொடங்குங்கள்',
    'existing_account': 'எனக்கு ஏற்கனவே கணக்கு உள்ளது',
    'hello_artisan': 'வணக்கம், கலைஞரே',
    'home_support': 'உங்கள் கலையை உலகத்திற்கு கொண்டு செல்வோம்.',
    'create_new_product': 'புதிய தயாரிப்பை உருவாக்கவும்',
    'create_support': 'உங்கள் தயாரிப்பை சந்தைத் தயாரான பட்டியலாக மாற்றுங்கள்',
    'total_products': 'மொத்த தயாரிப்புகள்',
    'recent_products': 'சமீபத்திய தயாரிப்புகள்',
    'view_all': 'அனைத்தையும் காண்க >',
  },
  'mr': {
    'app_name': 'कारागीरAI',
    'home_title': 'तुमची कला\nअधिक लोकांपर्यंत पोहोचवा.',
    'add_product': 'उत्पादन जोडा',
    'products': 'माझी उत्पादने',
    'create': 'तयार करा',
    'marketplace': 'बाजारपेठ',
    'profile': 'प्रोफाइल',
    'draft': 'मसुदा',
    'ready': 'तयार',
    'published': 'प्रकाशित',
    'save': 'उत्पादन जतन करा',
    'settings': 'सेटिंग्ज',
    'welcome_tagline': 'परंपरा आणि तंत्रज्ञान',
    'welcome_message': 'तुमचा आवाज आणि फोटो वापरून हस्तनिर्मित उत्पादनांसाठी बाजारपेठेसाठी तयार डिजिटल सूची बनवा.',
    'get_started': 'सुरू करा',
    'existing_account': 'माझे आधीपासून खाते आहे',
    'hello_artisan': 'नमस्कार, कारागीर',
    'home_support': 'तुमची कला जगापर्यंत पोहोचवूया.',
    'create_new_product': 'नवीन उत्पादन तयार करा',
    'create_support': 'तुमचे उत्पादन बाजारपेठेसाठी तयार सूचीमध्ये बदला',
    'total_products': 'एकूण उत्पादने',
    'recent_products': 'अलीकडील उत्पादने',
    'view_all': 'सर्व पहा >',
  },
  'bn': {
    'app_name': 'কারিগরAI',
    'home_title': 'আপনার শিল্পকে\nআরও মানুষের কাছে পৌঁছে দিন।',
    'add_product': 'পণ্য যোগ করুন',
    'products': 'আমার পণ্য',
    'create': 'তৈরি করুন',
    'marketplace': 'বাজার',
    'profile': 'প্রোফাইল',
    'draft': 'খসড়া',
    'ready': 'প্রস্তুত',
    'published': 'প্রকাশিত',
    'save': 'পণ্য সংরক্ষণ করুন',
    'settings': 'সেটিংস',
    'welcome_tagline': 'ঐতিহ্য ও প্রযুক্তি',
    'welcome_message': 'আপনার কণ্ঠ এবং ছবি ব্যবহার করে হস্তনির্মিত পণ্যের বাজার-প্রস্তুত ডিজিটাল তালিকা তৈরি করুন।',
    'get_started': 'শুরু করুন',
    'existing_account': 'আমার ইতিমধ্যে একটি অ্যাকাউন্ট আছে',
    'hello_artisan': 'নমস্কার, কারিগর',
    'home_support': 'আপনার শিল্পকে বিশ্বের কাছে পৌঁছে দিই।',
    'create_new_product': 'নতুন পণ্য তৈরি করুন',
    'create_support': 'আপনার পণ্যকে বাজার-প্রস্তুত তালিকায় রূপান্তর করুন',
    'total_products': 'মোট পণ্য',
    'recent_products': 'সাম্প্রতিক পণ্য',
    'view_all': 'সব দেখুন >',
  },
  'ml': {
    'app_name': 'കരിഗർAI',
    'home_title': 'നിങ്ങളുടെ കരകൗശലം\nകൂടുതൽ ആളുകളിലേക്ക് എത്തിക്കൂ.',
    'add_product': 'ഉൽപ്പന്നം ചേർക്കുക',
    'products': 'എന്റെ ഉൽപ്പന്നങ്ങൾ',
    'create': 'സൃഷ്ടിക്കുക',
    'marketplace': 'വിപണി',
    'profile': 'പ്രൊഫൈൽ',
    'draft': 'കരട്',
    'ready': 'തയ്യാർ',
    'published': 'പ്രസിദ്ധീകരിച്ചു',
    'save': 'ഉൽപ്പന്നം സംരക്ഷിക്കുക',
    'settings': 'ക്രമീകരണങ്ങൾ',
    'welcome_tagline': 'പാരമ്പര്യവും സാങ്കേതികവിദ്യയും',
    'welcome_message': 'നിങ്ങളുടെ ശബ്ദവും ചിത്രങ്ങളും ഉപയോഗിച്ച് കൈകൊണ്ട് നിർമ്മിച്ച ഉൽപ്പന്നങ്ങൾക്ക് വിപണി-സജ്ജമായ ഡിജിറ്റൽ ലിസ്റ്റിംഗുകൾ സൃഷ്ടിക്കുക.',
    'get_started': 'തുടങ്ങുക',
    'existing_account': 'എനിക്ക് ഇതിനകം ഒരു അക്കൗണ്ട് ഉണ്ട്',
    'hello_artisan': 'നമസ്കാരം, കരകൗശലക്കാരാ',
    'home_support': 'നിങ്ങളുടെ കലയെ ലോകത്തിലേക്ക് എത്തിക്കാം.',
    'create_new_product': 'പുതിയ ഉൽപ്പന്നം സൃഷ്ടിക്കുക',
    'create_support':
        'നിങ്ങളുടെ ഉൽപ്പന്നത്തെ വിപണി-സജ്ജമായ ലിസ്റ്റിംഗാക്കി മാറ്റുക',
    'total_products': 'ആകെ ഉൽപ്പന്നങ്ങൾ',
    'recent_products': 'സമീപകാല ഉൽപ്പന്നങ്ങൾ',
    'view_all': 'എല്ലാം കാണുക >',
  },
};

String languageCodeFor(String language) => languageCodes[language] ?? 'en';
