const supportedLanguages = [
  'English',
  'Hindi',
  'Kannada',
  'Telugu',
  'Tamil',
  'Marathi',
  'Bengali',
  'Malayalam',
];

const languageCodes = {
  'English': 'en',
  'Hindi': 'hi',
  'Kannada': 'kn',
  'Telugu': 'te',
  'Tamil': 'ta',
  'Marathi': 'mr',
  'Bengali': 'bn',
  'Malayalam': 'ml',
};

const translations = <String, Map<String, String>>{
  'en': {
    'app_name': 'KarigarAI',
    'home_title': 'Bring your craft\nto more people.',
    'add_product': 'Add Product',
    'products': 'My Products',
    'create': 'Create',
    'marketplace': 'Marketplace',
    'profile': 'Profile',
    'draft': 'Draft',
    'ready': 'Ready',
    'published': 'Published',
    'save': 'Save product',
    'settings': 'Settings',
    'welcome_tagline': 'Tradition Meets Technology',
    'welcome_message':
        'Turn your handmade products into market-ready digital listings using your voice and photos.',
    'get_started': 'Get Started',
    'existing_account': 'I Already Have an Account',
    'hello_artisan': 'Hello, Artisan',
    'home_support': 'Let us share your craft with the world.',
    'create_new_product': 'Create New Product',
    'create_support': 'Turn your product into a market-ready listing',
    'total_products': 'Total Products',
    'recent_products': 'Recent Products',
    'view_all': 'View All >',
  },
  'hi': {
    'app_name': 'कारीगरAI',
    'home_title': 'अपने शिल्प को\nऔर लोगों तक पहुँचाएँ।',
    'add_product': 'उत्पाद जोड़ें',
    'products': 'मेरे उत्पाद',
    'create': 'बनाएँ',
    'marketplace': 'बाज़ार',
    'profile': 'प्रोफ़ाइल',
    'draft': 'ड्राफ्ट',
    'ready': 'तैयार',
    'published': 'प्रकाशित',
    'save': 'उत्पाद सहेजें',
    'settings': 'सेटिंग्स',
  },
  'kn': {
    'app_name': 'ಕರಿಗರ್AI',
    'home_title': 'ನಿಮ್ಮ ಕರಕುಶಲವನ್ನು\nಹೆಚ್ಚಿನ ಜನರಿಗೆ ತಲುಪಿಸಿ.',
    'add_product': 'ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    'products': 'ನನ್ನ ಉತ್ಪನ್ನಗಳು',
    'create': 'ರಚಿಸಿ',
    'marketplace': 'ಮಾರುಕಟ್ಟೆ',
    'profile': 'ಪ್ರೊಫೈಲ್',
    'draft': 'ಕರಡು',
    'ready': 'ಸಿದ್ಧ',
    'published': 'ಪ್ರಕಟಿಸಲಾಗಿದೆ',
    'save': 'ಉತ್ಪನ್ನ ಉಳಿಸಿ',
    'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
  },
  'te': {
    'app_name': 'కరిగర్AI',
    'home_title': 'మీ కళను\nమరింత మందికి చేరవేయండి.',
    'add_product': 'ఉత్పత్తిని జోడించండి',
    'products': 'నా ఉత్పత్తులు',
    'create': 'సృష్టించండి',
    'marketplace': 'మార్కెట్',
    'profile': 'ప్రొఫైల్',
    'draft': 'చిత్తుప్రతి',
    'ready': 'సిద్ధం',
    'published': 'ప్రచురించబడింది',
    'save': 'ఉత్పత్తిని సేవ్ చేయండి',
    'settings': 'సెట్టింగ్‌లు',
  },
  'ta': {
    'app_name': 'கரிகர்AI',
    'home_title': 'உங்கள் கைவினையை\nமேலும் பலரிடம் கொண்டு செல்லுங்கள்.',
    'add_product': 'தயாரிப்பைச் சேர்க்கவும்',
    'products': 'என் தயாரிப்புகள்',
    'create': 'உருவாக்கு',
    'marketplace': 'சந்தை',
    'profile': 'சுயவிவரம்',
    'draft': 'வரைவு',
    'ready': 'தயார்',
    'published': 'வெளியிடப்பட்டது',
    'save': 'தயாரிப்பைச் சேமி',
    'settings': 'அமைப்புகள்',
  },
  'mr': {
    'app_name': 'कारागीरAI',
    'home_title': 'तुमची कला\nअधिक लोकांपर्यंत पोहोचवा.',
    'add_product': 'उत्पादन जोडा',
    'products': 'माझी उत्पादने',
    'create': 'तयार करा',
    'marketplace': 'बाजारपेठ',
    'profile': 'प्रोफाइल',
    'draft': 'मसुदा',
    'ready': 'तयार',
    'published': 'प्रकाशित',
    'save': 'उत्पादन जतन करा',
    'settings': 'सेटिंग्ज',
  },
  'bn': {
    'app_name': 'কারিগরAI',
    'home_title': 'আপনার শিল্পকে\nআরও মানুষের কাছে পৌঁছে দিন।',
    'add_product': 'পণ্য যোগ করুন',
    'products': 'আমার পণ্য',
    'create': 'তৈরি করুন',
    'marketplace': 'বাজার',
    'profile': 'প্রোফাইল',
    'draft': 'খসড়া',
    'ready': 'প্রস্তুত',
    'published': 'প্রকাশিত',
    'save': 'পণ্য সংরক্ষণ করুন',
    'settings': 'সেটিংস',
  },
  'ml': {
    'app_name': 'കരിഗർAI',
    'home_title': 'നിങ്ങളുടെ കരകൗശലം\nകൂടുതൽ ആളുകളിലേക്ക് എത്തിക്കൂ.',
    'add_product': 'ഉൽപ്പന്നം ചേർക്കുക',
    'products': 'എന്റെ ഉൽപ്പന്നങ്ങൾ',
    'create': 'സൃഷ്ടിക്കുക',
    'marketplace': 'വിപണി',
    'profile': 'പ്രൊഫൈൽ',
    'draft': 'കരട്',
    'ready': 'തയ്യാർ',
    'published': 'പ്രസിദ്ധീകരിച്ചു',
    'save': 'ഉൽപ്പന്നം സംരക്ഷിക്കുക',
    'settings': 'ക്രമീകരണങ്ങൾ',
  },
};

String languageCodeFor(String language) => languageCodes[language] ?? 'en';
